server:
  port: 8081
spring:
  redis:
    host: 117.72.91.159
    port: 16379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.91.159:13306/oj?useSSL=false&serverTimezone=UTC
    username: root
    password: "123456"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case=true:

