server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    host: 192.168.227.100
    port: 6379
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 3000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj?useSSL=false&serverTimezone=UTC
    username: root
    password: "123456"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case=true:
  mapper-locations: classpath*:mapper/*.xml
minio:
  endpoint: http://117.72.91.159:8999
  access-key: root
  secret-key: 123456789
  bucketName: user01


